agv_numbers:
    - "61"
    - "62"
    - "63"
agv_points:
    "4":
        - "4"
        - "5"
        - "6"
        - "7"
        - "22"
        - "24"
        - "25"
        - "26"
        - "28"
        - "29"
        - "30"
        - "32"
        - "33"
        - "34"
        - "39"
        - "40"
        - "41"
        - "51"
        - "69"
        - "70"
        - 1线放料点
        - 1线中转点
        - 2线放料点
        - 2线中转点
        - 3线放料点
        - 3线中转点
        - 5线放料点
        - 5线中转点
        - 6线放料点
        - 6线中转点
        - 7线放料点
        - 7线中转点
        - 8线放料点
        - 8线中转点
        - 暂存12
        - 暂存34
        - 暂存34（2）
        - 暂存56
        - 暂存78
    "5":
        - "8"
        - "10"
        - "11"
        - "17"
        - "18"
        - "20"
        - "31"
        - "36"
        - "37"
        - "38"
        - "42"
        - "43"
        - "44"
        - "46"
        - "47"
        - "48"
        - "49"
        - "50"
        - "52"
        - "53"
        - "54"
        - "56"
        - "57"
        - "58"
        - "59"
        - "60"
        - "62"
        - "63"
        - "64"
        - "71"
        - 电梯口等待位
        - '分盘区1 '
        - 分盘区2
        - 分盘区3
        - 分盘区4
        - 货架点1
        - 旋转点
        - 旋转点2
        - 旋转点3
        - 旋转点4
        - 旋转点5
        - 旋转点6
        - 旋转点7
        - 旋转点8
map_config:
    map_id_4_floor: 四楼1
    map_id_5_floor: 五楼1
